# Generated by Django 5.2.7 on 2026-06-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification_delete_emailotpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='experience_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='analysis',
            name='hr_questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysis',
            name='job_suitability',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='analysis',
            name='project_analysis',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysis',
            name='project_questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysis',
            name='recruiter_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='skill_gap_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='analysis',
            name='technical_questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='analysis',
            name='verdict',
            field=models.CharField(default='Moderate Match', max_length=100),
        ),
    ]
