# Generated by Django 5.2.7 on 2026-06-27 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_analysis_experience_analysis_analysis_hr_questions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_profile_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_profile_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='login_provider',
            field=models.CharField(default='email', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='LinkedInProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_id', models.CharField(max_length=255, unique=True)),
                ('linkedin_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('profile_url', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_picture', models.CharField(blank=True, max_length=500, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'linkedin_profiles',
            },
        ),
    ]
